// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchulPlanerBot.Business;

#nullable disable

namespace SchulPlanerBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20250516181310_ObjectsIn")]
    partial class ObjectsIn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchulPlanerBot.Business.Models.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<TimeSpan>("DeleteHomeworksAfterDue")
                        .HasColumnType("interval");

                    b.Property<string>("NotificationLocale")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("SchulPlanerBot.Business.Models.Homework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreatedBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Due")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LastModifiedBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Homeworks");
                });

            modelBuilder.Entity("SchulPlanerBot.Business.Models.HomeworkSubscription", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("AnySubject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.PrimitiveCollection<string[]>("Exclude")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.PrimitiveCollection<string[]>("Include")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("HomeworkSubscriptions");
                });

            modelBuilder.Entity("SchulPlanerBot.Business.Models.Guild", b =>
                {
                    b.OwnsMany("SchulPlanerBot.Business.Models.Notification", "Notifications", b1 =>
                        {
                            b1.Property<decimal>("GuildId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<TimeSpan>("Between")
                                .HasColumnType("interval");

                            b1.Property<decimal>("ChannelId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<TimeSpan>("ObjectsIn")
                                .HasColumnType("interval");

                            b1.Property<DateTimeOffset>("StartAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("GuildId", "__synthesizedOrdinal");

                            b1.ToTable("Guilds");

                            b1.ToJson("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("GuildId");
                        });

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SchulPlanerBot.Business.Models.Homework", b =>
                {
                    b.HasOne("SchulPlanerBot.Business.Models.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchulPlanerBot.Business.Models.HomeworkSubscription", b =>
                {
                    b.HasOne("SchulPlanerBot.Business.Models.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
