- op: add
  path: "/spec/template/spec/containers/0/livenessProbe"
  value:
    httpGet:
      path: "/alive"
      port: http
    failureThreshold: 30
    periodSeconds: 10
- op: add
  path: "/spec/template/spec/containers/0/readinessProbe"
  value:
    httpGet:
      path: "/health"
      port: http
    failureThreshold: 30
    periodSeconds: 10